spring.application.name=apacheagedemo


spring.datasource.url=jdbc:postgresql://localhost:5432/age?currentSchema=ag_catalog,public
spring.datasource.username=age
spring.datasource.password=age
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true   